# Site settings
title: Ben Rifkind
email: ben (dot) rifkind (at) gmail (dot) com
description: > # this means to ignore newlines until "baseurl:"
  Recent phD graduate in probability from the University of Toronto. Now trying to bridge
  the gap from academia to industry by learning statistics, data analysis, and R. This website
  will hosts writeups of the projects I'm working on.

  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: 
github_username: benrifkind 
# Build settings
markdown: kramdown
